language: csharp
solution: ParadoxDbCopier.sln
install:
  - nuget restore ParadoxDbCopier.sln
  - nuget install xunit.runners -Version 2.3.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ParadoxDbCopier.sln
  - mono ./testrunner/xunit.runners.2.3.1/tools/xunit.console.clr4.exe ./ParadoxDbCopierUnitTests/bin/Release/netcoreapp2.0/ParadoxDbCopierUnitTests.dll